#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Build the hero terminal demo of the main page from a real, sanitized log.

Two stages live here (plan 2026-08-13, F0.4):

  --sanitize --raw <file>   stage B: raw log (kept OUTSIDE this repo) -> docs/hero-demo.sanitized.txt
                            allowlist of publicly safe lines + masking + secret scan.
  (default)                 stage C: docs/hero-demo.sanitized.txt -> assets/hero-demo.js
  --check                   stage C in verify mode: regenerating must reproduce the
                            committed assets/hero-demo.js byte for byte.

The generator is self-contained inside the repository: the committed sanitized
source is the only input, so the golden check reproduces on any machine.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SANITIZED = REPO / "docs" / "hero-demo.sanitized.txt"
FIXTURE = REPO / "assets" / "hero-demo.js"

# --- allowlist: only these line shapes may ever reach the public site ----------
# Anything not matched here is dropped, no exceptions. Inventories of skills, MCP
# servers, client contours and sessions are not a publishable data class at all.
ALLOW = [
    r"^\$ claude --version$",
    r"^\$ node --version$",
    r"^\$ claude doctor$",
    r'^\$ python -c "check workstation config"$',
    r"^\d+\.\d+\.\d+ \(Claude Code\)$",
    r"^v\d+\.\d+\.\d+$",
    r"^Claude Code doctor$",
    r"^Running: native \(\d+\.\d+\.\d+\)$",
    r"^Platform: [a-z0-9\-]+$",
    r"^Path: .+claude\.exe$",
    r"^Config install method: [a-z\-]+$",
    r"^Search: OK \(bundled\)$",
    r"^Auto-updates: (enabled|disabled)$",
    r"^No installation issues found\.$",
    r"^settings\.json: (present|missing)$",
    r"^CLAUDE\.md: (present|missing)$",
    r"^status: (ready|not configured)$",
]

SECRET_RE = re.compile(r"AIzaSy|sk-[A-Za-z0-9]|hf_[A-Za-z0-9]|ghp_|xox[baprs]-|-----BEGIN|"
                       r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")


def mask(line: str) -> str:
    """Home-relative paths only; no usernames, no absolute paths, no hostnames."""
    line = re.sub(r"[A-Za-z]:\\Users\\[^\\\s]+", "~", line)
    line = re.sub(r"/home/[^/\s]+", "~", line)
    line = re.sub(r"[A-Za-z]:\\[^\s]*\\(?=[^\\\s]+$)", "~\\\\", line)
    return line


def sanitize(raw_path: Path) -> str:
    raw_bytes = raw_path.read_bytes()
    sha = hashlib.sha256(raw_bytes).hexdigest()
    kept: list[str] = []
    for line in raw_bytes.decode("utf-8").splitlines():
        line = line.rstrip()
        masked = mask(line)
        if any(re.match(p, masked) for p in ALLOW):
            kept.append(masked)

    body = "\n".join(kept)
    leaks = SECRET_RE.findall(body)
    if leaks:
        raise SystemExit(f"[build_hero_demo] secret-scan FAILED: {leaks}")
    if not kept:
        raise SystemExit("[build_hero_demo] nothing passed the allowlist — check the raw log")

    header = (
        "# hero demo — sanitized source of the terminal in the first screen.\n"
        "# Real output of a real check run, filtered through the allowlist in\n"
        "# scripts/build_hero_demo.py; usernames, absolute paths, ids and hostnames are masked.\n"
        f"# raw-source-sha256: {sha}\n"
        "# The raw log is kept outside this repository (provenance artefact).\n"
    )
    return header + body + "\n"


def frames(sanitized_text: str) -> list[dict]:
    out: list[dict] = []
    for line in sanitized_text.splitlines():
        if not line or line.startswith("#"):
            continue
        if line.startswith("$ "):
            out.append({"s": line[2:], "t": "cmd"})
        elif line.startswith("status: ") or line == "No installation issues found.":
            out.append({"s": line, "t": "ok"})
        else:
            out.append({"s": line, "t": "out"})
    return out


def render_fixture(sanitized_text: str) -> str:
    data = json.dumps(frames(sanitized_text), ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"))
    return (
        "/* generated by scripts/build_hero_demo.py from docs/hero-demo.sanitized.txt — do not edit by hand */\n"
        "window.HERO_DEMO=" + data + ";\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sanitize", action="store_true", help="stage B: raw log -> sanitized source")
    ap.add_argument("--raw", help="path to the raw log (outside the repo)")
    ap.add_argument("--check", action="store_true", help="verify the committed fixture is reproducible")
    args = ap.parse_args()

    if args.sanitize:
        if not args.raw:
            raise SystemExit("[build_hero_demo] --sanitize needs --raw <file>")
        text = sanitize(Path(args.raw))
        SANITIZED.parent.mkdir(parents=True, exist_ok=True)
        SANITIZED.write_text(text, encoding="utf-8", newline="\n")
        print(f"[build_hero_demo] written {SANITIZED} ({len(text.splitlines())} lines)")

    text = SANITIZED.read_text(encoding="utf-8")
    leaks = SECRET_RE.findall(text)
    if leaks:
        raise SystemExit(f"[build_hero_demo] secret-scan FAILED on sanitized source: {leaks}")

    fixture = render_fixture(text)
    if args.check:
        current = FIXTURE.read_text(encoding="utf-8") if FIXTURE.exists() else ""
        if current != fixture:
            print("[build_hero_demo] MISMATCH: assets/hero-demo.js is not reproducible")
            return 1
        print(f"[build_hero_demo] golden OK: {FIXTURE.name} byte-identical, "
              f"{len(frames(text))} frames, secret-scan 0")
        return 0

    FIXTURE.write_text(fixture, encoding="utf-8", newline="\n")
    print(f"[build_hero_demo] written {FIXTURE} ({len(frames(text))} frames)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
